language: php
php:
 - 5.4
services:
 - mysql
sudo: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - php -S localhost:8000 -t ./ &
  - "sh -e /etc/init.d/xvfb start"
script:
  - phpunit tests/cases/InstallTest.php
